# Generated by Django 4.2.7 on 2023-11-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_dummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listsong',
            name='for_singer',
            field=models.CharField(default='', max_length=30),
        ),
    ]
