# Generated by Django 4.2.7 on 2023-11-26 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('get_latlong', models.BooleanField(default=False, verbose_name='Automatic Get Address')),
            ],
        ),
        migrations.CreateModel(
            name='OperationHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_bus_route', models.CharField(max_length=3)),
                ('route', models.ManyToManyField(to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='EndRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_bus_route', models.CharField(max_length=3)),
                ('route', models.ManyToManyField(to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bus', models.CharField(max_length=3)),
                ('round_end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.endroute')),
                ('route_start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.startroute')),
            ],
        ),
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('weekend', models.BooleanField(default=False)),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.busroute')),
            ],
        ),
    ]
