# Generated by Django 4.2.7 on 2023-11-27 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_businfo_bus_operation_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointerOperationHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.operationhour')),
            ],
        ),
        migrations.AlterField(
            model_name='busoperationhour',
            name='operation_hour_rel',
            field=models.ManyToManyField(to='base.pointeroperationhour'),
        ),
    ]
