# Generated by Django 4.2.7 on 2023-11-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_businfo_busroute_operationhour_delete_bussesinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='weekend',
            field=models.BooleanField(default=False),
        ),
    ]
