# Generated by Django 4.2.7 on 2023-11-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pointeroperationhour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationhour',
            options={'ordering': ['start', 'end']},
        ),
    ]
