# Generated by Django 4.2.7 on 2023-11-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_operationhour_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointeroperationhour',
            name='operation_hour',
        ),
        migrations.RemoveField(
            model_name='businfo',
            name='bus_operation_hour',
        ),
        migrations.AddField(
            model_name='businfo',
            name='operation_hour',
            field=models.ManyToManyField(to='base.operationhour'),
        ),
        migrations.DeleteModel(
            name='BusOperationHour',
        ),
        migrations.DeleteModel(
            name='PointerOperationHour',
        ),
    ]
