# Generated by Django 4.2.7 on 2023-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_businfo_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhour',
            name='end',
            field=models.TimeField(blank=True),
        ),
    ]
