# Generated by Django 4.2.7 on 2023-11-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_operationhour_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhour',
            name='bus_name',
        ),
    ]
