# Generated by Django 4.2.7 on 2023-11-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_operationhour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationhour',
            options={'ordering': [models.OrderBy(models.F('start'), nulls_last=True)]},
        ),
    ]
