# Generated by Django 4.2.7 on 2023-11-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_operationhour_bus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='route',
        ),
        migrations.CreateModel(
            name='StartRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_bus_route', models.CharField(max_length=3)),
                ('route', models.ManyToManyField(to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='EndRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_bus_route', models.CharField(max_length=3)),
                ('route', models.ManyToManyField(to='base.address')),
            ],
        ),
        migrations.AddField(
            model_name='busroute',
            name='round_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.endroute'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.startroute'),
        ),
    ]
