# Generated by Django 4.2.7 on 2023-11-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_busroute_route_startroute_endroute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationhour',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationhour',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
