# Generated by Django 4.2.7 on 2023-11-27 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_operationhour_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationhour',
            name='end_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationhour',
            name='start_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operationhour',
            name='start',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
