# Generated by Django 4.2.7 on 2023-11-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_operationhour_end_alter_operationhour_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHourBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.businfo')),
                ('bus_operation_hour', models.ManyToManyField(to='base.operationhour')),
            ],
        ),
    ]
