# Generated by Django 4.2.7 on 2023-11-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_operationhour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfo',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='startroute',
            options={'ordering': ['for_bus_route']},
        ),
        migrations.AlterField(
            model_name='businfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='type_bus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='endroute',
            name='for_bus_route',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='startroute',
            name='for_bus_route',
            field=models.CharField(max_length=20),
        ),
    ]
