# Generated by Django 4.2.7 on 2023-11-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_operationhourbus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='operation_hour',
        ),
    ]
