# Generated by Django 4.2.7 on 2023-11-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_businfo_operation_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhourbus',
            name='bus_name',
        ),
        migrations.AddField(
            model_name='businfo',
            name='operation_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.operationhourbus'),
        ),
        migrations.AddField(
            model_name='operationhourbus',
            name='for_bus',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
