# Generated by Django 4.2.7 on 2023-11-28 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_businfo_options_alter_startroute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_bus_route', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='startroute',
            name='route',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='round_end',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='route_start',
        ),
        migrations.DeleteModel(
            name='EndRoute',
        ),
        migrations.DeleteModel(
            name='StartRoute',
        ),
        migrations.AddField(
            model_name='pointeraddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='route',
            field=models.ManyToManyField(to='base.pointeraddress'),
        ),
    ]
