# Generated by Django 4.2.7 on 2023-11-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_busroute_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointeraddress',
            name='position',
            field=models.BigIntegerField(default=0),
        ),
    ]
